### PR TITLE
Build kubectl plugin for macOS.

### PR DESCRIPTION
**Pull request by reitermarkus**
Closes https://github.com/openebs/mayastor-control-plane/issues/230.

### CODE REVIEW

**Review by tiagolobocastro — COMMENTED** [review]
@reitermarkus great thanks but please note we can't test macos atm so the plugin will not be "officially" supported until we're able to do so.
Could you please change the commit to the conventional commits?

**Comment by tiagolobocastro** [comment]
Sorry missed you new push. Could you please fix your commits in this repo as well?
If you use the nix-shell of the repo that installs the pre-commit hook which should check your commits.

**Comment by reitermarkus** [comment]
@tiagolobocastro, can this be merged?

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro, can this be merged?
I think so :)

bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@reitermarkus, sorry thought this had gone in. The CI should be working - would you be able to refactor your changes to the current layout? Otherwise I can pick this up for you? Thank you

**Comment by tiagolobocastro** [comment]
@reitermarkus, sorry thought this had gone in. The CI should be working - would you be able to refactor your changes to the current layout? Otherwise I can pick this up for you? Thank you

**Comment by tiagolobocastro** [comment]
@reitermarkus things have changed a bit, and looks like the macos build on GHA was not passing statically, so let's merge this with dynamic compilation to start with. The windows build is currently broken too :/
bors merge

**Comment by reitermarkus** [comment]
@tiagolobocastro, thanks for picking this up and merging!

**Pull request merged**
