### PR TITLE
docs: (readme.md)

### PR DESCRIPTION
**Pull request by GlennBullingham**
- Use capitalisation consistent with established project style: (Mayastor not MayaStor)
- Add an experimental feature notice

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]
Thanks @GlennBullingham

**Review by tiagolobocastro — APPROVED** [review]
:+1:

**Comment by tiagolobocastro** [comment]
@GlennBullingham you'll need to tweak the commit subject

**Comment by paulyoong** [comment]
bors merge

**Pull request merged**
